const test = require('node:test'); const assert = require('node:assert/strict'); const crypto = require('crypto');
process.env.NODE_ENV = 'test'; process.env.JWT_SECRET = 'phase8-test-only-secret'; process.env.QUESTION_PAPER_MASTER_KEY = crypto.randomBytes(32).toString('base64'); process.env.STORAGE_PROVIDER = 'local';
const app = require('../src/app'); const connectDatabase = require('../src/config/database'); const User = require('../src/models/User'); const QuestionPaper = require('../src/models/QuestionPaper'); const QuestionPaperReview = require('../src/models/QuestionPaperReview'); const QuestionPaperApproval = require('../src/models/QuestionPaperApproval'); const AuditLog = require('../src/models/AuditLog'); const storage = require('../src/services/questionPaperStorageService'); const tokens = require('../src/services/tokenService'); const mongoose = require('mongoose');
let server, base, users = {}, auth = {};
const request = async (path, options = {}) => { const r = await fetch(base + path, { ...options, headers: { 'content-type': 'application/json', ...(options.headers || {}) } }); return { status: r.status, body: await r.json() }; }; const headers = token => ({ authorization: `Bearer ${token}` });
async function paper(title) { const created = await request('/question-papers', { method: 'POST', headers: headers(auth.setter), body: JSON.stringify({ title, examName: 'Phase 8 Exam', subject: 'Security' }) }); const id = created.body.paper.id; const form = new FormData(); form.append('file', new Blob(['%PDF-1.4\nphase8'], { type: 'application/pdf' }), 'phase8.pdf'); assert.equal((await fetch(base + `/question-papers/${id}/upload`, { method: 'POST', headers: headers(auth.setter), body: form })).status, 200); assert.equal((await request(`/question-papers/${id}/submit`, { method: 'POST', headers: headers(auth.setter) })).status, 200); assert.equal((await request(`/reviewer/question-papers/${id}/claim`, { method: 'POST', headers: headers(auth.reviewer) })).status, 200); assert.equal((await request(`/reviewer/question-papers/${id}/approve`, { method: 'POST', headers: headers(auth.reviewer), body: JSON.stringify({ comment: 'Reviewer approval' }) })).status, 200); return id; }
test.before(async () => { await connectDatabase(); const keys = { QUESTION_SETTER: 'setter', REVIEWER: 'reviewer', SECURITY_OFFICER: 'security', EXAM_AUTHORITY: 'authority', EXAM_CENTER: 'centre' }; for (const role of Object.keys(keys)) { const u = await User.create({ name: `Phase8 ${role}`, email: `phase8-${role.toLowerCase()}@example.com`, passwordHash: 'hash', role }); users[role] = u; auth[keys[role]] = tokens.issueToken(u); } server = app.listen(0); base = `http://127.0.0.1:${server.address().port}/api`; });
test.after(async () => { const papers = await QuestionPaper.find({ title: /^Phase8 Test/ }).select('+storageProvider'); await Promise.all(papers.map(p => storage.getStorage(p.storageProvider || 'local').remove(p.storageKey).catch(() => {}))); await QuestionPaperReview.deleteMany({ paperId: { $in: papers.map(p => p._id) } }); await QuestionPaperApproval.deleteMany({ paperId: { $in: papers.map(p => p._id) } }); await QuestionPaper.deleteMany({ title: /^Phase8 Test/ }); await User.deleteMany({ email: /phase8-/ }); await new Promise(resolve => server.close(resolve)); await mongoose.disconnect(); });
test('Phase 8 RBAC and atomic security claims are server controlled', async () => { assert.equal((await request('/security-officer/dashboard/stats', { headers: headers(auth.security) })).status, 200); assert.equal((await request('/security-officer/dashboard/stats', { headers: headers(auth.setter) })).status, 403); const id = await paper('Phase8 Test Security Claim'); assert.equal((await request(`/security-officer/question-papers/${id}/claim`, { method: 'POST', headers: headers(auth.security) })).status, 200); assert.equal((await request(`/security-officer/question-papers/${id}/claim`, { method: 'POST', headers: headers(auth.security) })).status, 409); assert.equal((await request(`/security-officer/question-papers/${id}/reject`, { method: 'POST', headers: headers(auth.security), body: JSON.stringify({ comment: 'no' }) })).status, 400); });
test('approval chain locks only after independent authority approval', async () => { const id = await paper('Phase8 Test Full Chain'); assert.equal((await request(`/exam-authority/question-papers/${id}/claim`, { method: 'POST', headers: headers(auth.authority) })).status, 409); assert.equal((await request(`/security-officer/question-papers/${id}/claim`, { method: 'POST', headers: headers(auth.security) })).status, 200); assert.equal((await request(`/security-officer/question-papers/${id}/approve`, { method: 'POST', headers: headers(auth.security), body: JSON.stringify({ comment: 'Security approved' }) })).status, 200); assert.equal((await request(`/exam-authority/question-papers/${id}/claim`, { method: 'POST', headers: headers(auth.authority) })).status, 200); const final = await request(`/exam-authority/question-papers/${id}/approve`, { method: 'POST', headers: headers(auth.authority), body: JSON.stringify({ comment: 'Final approval' }) }); assert.equal(final.status, 200); assert.equal(final.body.paper.status, 'LOCKED'); assert.equal(final.body.paper.isLocked, true); assert.equal((await request(`/question-papers/${id}/submit`, { method: 'POST', headers: headers(auth.setter) })).status, 409); assert.ok(await AuditLog.exists({ action: 'QUESTION_PAPER_LOCKED', targetId: id })); });
