const mongoose = require('mongoose');
const QuestionPaper = require('../models/QuestionPaper');
const QuestionPaperApproval = require('../models/QuestionPaperApproval');
const { audit } = require('../services/auditService');
const storage = require('../services/questionPaperStorageService'); const blockchain = require('../services/blockchainService'); const { blockchainEnabled } = require('../config/env');

const validId = id => mongoose.isObjectIdOrHexString(id);
const CONFIG = {
  SECURITY_OFFICER: { role: 'SECURITY_OFFICER', available: 'REVIEWER_APPROVED', reviewing: 'SECURITY_REVIEW', approved: 'SECURITY_APPROVED', rejected: 'SECURITY_REJECTED', id: 'securityOfficerId', assignedAt: 'securityReviewAssignedAt', reviewedAt: 'securityReviewedAt', comment: 'securityReviewComment', previousIds: ['reviewerId'], prefix: 'SECURITY_REVIEW' },
  EXAM_AUTHORITY: { role: 'EXAM_AUTHORITY', available: 'SECURITY_APPROVED', reviewing: 'AUTHORITY_REVIEW', approved: 'LOCKED', rejected: 'AUTHORITY_REJECTED', id: 'examAuthorityId', assignedAt: 'authorityReviewAssignedAt', reviewedAt: 'finalApprovedAt', comment: 'authorityReviewComment', previousIds: ['reviewerId', 'securityOfficerId'], prefix: 'AUTHORITY_REVIEW' },
};
function safePaper(paper) { return { id: paper._id, title: paper.title, examName: paper.examName, examCode: paper.examCode, subject: paper.subject, questionPaperType: paper.questionPaperType, fileOriginalName: paper.fileOriginalName, fileMimeType: paper.fileMimeType, fileSize: paper.fileSize, hasFile: Boolean(paper.storageKey), isEncrypted: Boolean(paper.storageKey && String(paper.fileStoredName || '').endsWith('.enc')), integrityProtected: Boolean(paper.storageKey && String(paper.fileStoredName || '').endsWith('.enc')), status: paper.status, submittedAt: paper.submittedAt, reviewedAt: paper.reviewedAt, securityReviewedAt: paper.securityReviewedAt, finalApprovedAt: paper.finalApprovedAt, reviewComment: paper.reviewComment, securityReviewComment: paper.securityReviewComment, authorityReviewComment: paper.authorityReviewComment, isLocked: paper.isLocked, lockedAt: paper.lockedAt, releaseStatus: paper.releaseStatus, scheduledReleaseAt: paper.scheduledReleaseAt, submittedBy: paper.createdBy?.name }; }
function commentFrom(request, required) { const value = typeof request.body?.comment === 'string' ? request.body.comment.trim() : ''; return required && value.length < 5 ? null : value || null; }
function releaseTimestamp(value) {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(value)) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}
function stageController(stage) {
  const c = CONFIG[stage];
  const assignedQuery = userId => ({ $or: [{ status: c.available, createdBy: { $ne: userId } }, { status: { $in: [c.reviewing, c.approved, c.rejected, 'LOCKED'] }, [c.id]: userId }] });
  const conflicts = userId => ({ $and: [{ createdBy: { $ne: userId } }, ...c.previousIds.map(field => ({ $or: [{ [field]: null }, { [field]: { $ne: userId } }] }))] });
  async function denied(request, response, action, code = 404) { await audit(request, action, { targetType: 'QuestionPaper', targetId: request.params.id }); return response.status(code).json({ success: false, message: 'Question paper is not available for this approval stage.' }); }
  async function findAccessible(request, response, action) { if (!validId(request.params.id)) return denied(request, response, `${c.prefix}_PAPER_ACCESS_DENIED`); const paper = await QuestionPaper.findOne({ _id: request.params.id, ...assignedQuery(request.user._id) }).select(`+${c.id} +reviewerId +securityOfficerId`).populate('createdBy', 'name'); if (!paper) return denied(request, response, `${c.prefix}_PAPER_ACCESS_DENIED`); return paper; }
  return {
    async dashboardStats(request, response, next) { try { const id = request.user._id; const [pending, underReview, approved, rejected, recent] = await Promise.all([QuestionPaper.countDocuments({ status: c.available, createdBy: { $ne: id }, ...conflicts(id) }), QuestionPaper.countDocuments({ status: c.reviewing, [c.id]: id }), QuestionPaper.countDocuments({ status: c.approved, [c.id]: id }), QuestionPaper.countDocuments({ status: c.rejected, [c.id]: id }), QuestionPaperApproval.find({ actorId: id, stage }).sort({ createdAt: -1 }).limit(5).populate('paperId', 'title').lean()]); await audit(request, `${c.prefix}_DASHBOARD_VIEWED`); response.json({ success: true, stats: { pending, underReview, approved, rejected }, recent: recent.map(x => ({ action: x.action, comment: x.comment, createdAt: x.createdAt, paperTitle: x.paperId?.title || 'Question paper' })) }); } catch (e) { next(e); } },
    async listPapers(request, response, next) { try { const papers = await QuestionPaper.find({ ...assignedQuery(request.user._id), ...conflicts(request.user._id) }).select(`+${c.id} +reviewerId +securityOfficerId`).populate('createdBy', 'name').sort({ updatedAt: -1 }).lean(); response.json({ success: true, papers: papers.map(safePaper) }); } catch (e) { next(e); } },
    async getPaper(request, response, next) { try { const paper = await findAccessible(request, response, 'VIEW'); if (!paper) return; response.json({ success: true, paper: safePaper(paper) }); } catch (e) { next(e); } },
    async claimPaper(request, response, next) { try { if (!validId(request.params.id)) return denied(request, response, `${c.prefix}_PAPER_ACCESS_DENIED`); const now = new Date(); const paper = await QuestionPaper.findOneAndUpdate({ _id: request.params.id, status: c.available, [c.id]: null, ...conflicts(request.user._id) }, { $set: { status: c.reviewing, [c.id]: request.user._id, [c.assignedAt]: now, [c.reviewedAt]: null, [c.comment]: null } }, { new: true }).select(`+${c.id} +reviewerId +securityOfficerId`).populate('createdBy', 'name'); if (!paper) { const own = await QuestionPaper.exists({ _id: request.params.id, createdBy: request.user._id }); await audit(request, own ? 'SELF_APPROVAL_DENIED' : 'INVALID_APPROVAL_TRANSITION', { targetType: 'QuestionPaper', targetId: request.params.id }); return response.status(own ? 403 : 409).json({ success: false, message: own ? 'You cannot approve your own question paper.' : 'Question paper is no longer available for this approval stage.' }); } await QuestionPaperApproval.create({ paperId: paper._id, stage, action: 'CLAIMED', actorId: request.user._id }); await audit(request, `${c.prefix}_CLAIMED`, { targetType: 'QuestionPaper', targetId: paper.id }); response.json({ success: true, paper: safePaper(paper) }); } catch (e) { next(e); } },
    async decidePaper(request, response, next, action) { try { if (!validId(request.params.id)) return denied(request, response, `${c.prefix}_PAPER_ACCESS_DENIED`); const comment = commentFrom(request, action === 'REJECTED'); if (action === 'REJECTED' && !comment) return response.status(400).json({ success: false, message: 'A rejection reason of at least 5 characters is required.' }); const now = new Date(); const set = { status: action === 'APPROVED' ? c.approved : c.rejected, [c.reviewedAt]: now, [c.comment]: comment }; if (stage === 'EXAM_AUTHORITY' && action === 'APPROVED') Object.assign(set, { isLocked: true, lockedAt: now, lockedBy: request.user._id }); const paper = await QuestionPaper.findOneAndUpdate({ _id: request.params.id, status: c.reviewing, [c.id]: request.user._id, ...conflicts(request.user._id) }, { $set: set }, { new: true }).select(`+${c.id} +reviewerId +securityOfficerId`).populate('createdBy', 'name'); if (!paper) { const own = await QuestionPaper.exists({ _id: request.params.id, createdBy: request.user._id }); await audit(request, own ? 'SELF_APPROVAL_DENIED' : 'INVALID_APPROVAL_TRANSITION', { targetType: 'QuestionPaper', targetId: request.params.id, metadata: { action } }); return response.status(own ? 403 : 409).json({ success: false, message: own ? 'You cannot approve your own question paper.' : 'Question paper is not assigned for this approval action.' }); } await QuestionPaperApproval.create({ paperId: paper._id, stage, action, actorId: request.user._id, comment }); if (stage === 'EXAM_AUTHORITY' && action === 'APPROVED') await QuestionPaperApproval.create({ paperId: paper._id, stage, action: 'LOCKED', actorId: request.user._id }); await audit(request, `${c.prefix}_${action === 'APPROVED' ? 'APPROVED' : 'REJECTED'}`, { targetType: 'QuestionPaper', targetId: paper.id }); if (stage === 'EXAM_AUTHORITY' && action === 'APPROVED') await audit(request, 'QUESTION_PAPER_LOCKED', { targetType: 'QuestionPaper', targetId: paper.id }); response.json({ success: true, paper: safePaper(paper) }); } catch (e) { next(e); } },
    async listApprovals(request, response, next) { try { const paper = await findAccessible(request, response, 'HISTORY'); if (!paper) return; const approvals = await QuestionPaperApproval.find({ paperId: paper._id }).sort({ createdAt: 1 }).populate('actorId', 'name').lean(); response.json({ success: true, approvals: approvals.map(x => ({ stage: x.stage, action: x.action, comment: x.comment, createdAt: x.createdAt, actorName: x.actorId?.name || 'Approver' })) }); } catch (e) { next(e); } },
    approvePaper(request, response, next) { return this.decidePaper(request, response, next, 'APPROVED'); },
    rejectPaper(request, response, next) { return this.decidePaper(request, response, next, 'REJECTED'); },
  };
}
const securityOfficer = stageController('SECURITY_OFFICER'); const examAuthority = stageController('EXAM_AUTHORITY'); const authorityDecide = examAuthority.decidePaper;
examAuthority.decidePaper = async function(request, response, next, action) { await authorityDecide(request, response, next, action); if (!blockchainEnabled || action !== 'APPROVED') return; try { const paper = await QuestionPaper.findById(request.params.id).select('+storageProvider +encryptedFileHash'); if (!paper || paper.status !== 'LOCKED') return; await audit(request, 'BLOCKCHAIN_ANCHOR_REQUESTED', { targetType: 'QuestionPaper', targetId: paper.id }); const ciphertext = await storage.getStorage(paper.storageProvider || 'local').getEncryptedFile(paper.storageKey); const result = await blockchain.anchor(paper, ciphertext); if (result.skipped) return; Object.assign(paper, { blockchainStatus: 'ANCHORED', blockchainPaperIdHash: result.paperIdHash, blockchainArtifactHash: result.contentHash, blockchainTransactionHash: result.transactionHash || null, blockchainBlockNumber: result.blockNumber || null, blockchainChainId: result.chainId || null, blockchainContractAddress: result.contractAddress || null, blockchainAnchoredAt: result.anchoredAt || new Date(), blockchainFailureReason: null }); await paper.save(); await audit(request, 'BLOCKCHAIN_ANCHOR_CONFIRMED', { targetType: 'QuestionPaper', targetId: paper.id }); } catch (error) { const paper = await QuestionPaper.findById(request.params.id); if (paper?.status === 'LOCKED') { paper.blockchainStatus = 'FAILED'; paper.blockchainFailureReason = error.code === 'BLOCKCHAIN_HASH_MISMATCH' ? 'Encrypted artifact integrity verification failed.' : 'Blockchain anchoring failed.'; await paper.save(); } await audit(request, error.code === 'BLOCKCHAIN_HASH_MISMATCH' ? 'BLOCKCHAIN_HASH_MISMATCH' : 'BLOCKCHAIN_ANCHOR_FAILED', { targetType: 'QuestionPaper', targetId: request.params.id }); } };
examAuthority.scheduleRelease = async function(request, response, next) {
  try {
    if (!validId(request.params.id)) return response.status(404).json({ success: false, message: 'Question paper not found.' });
    const scheduledReleaseAt = releaseTimestamp(request.body?.scheduledReleaseAt);
    if (!scheduledReleaseAt) {
      await audit(request, 'RELEASE_SCHEDULE_DENIED', { targetType: 'QuestionPaper', targetId: request.params.id, metadata: { reason: 'invalid_timestamp' } });
      return response.status(400).json({ success: false, message: 'scheduledReleaseAt must be an ISO-8601 timestamp with a UTC offset.' });
    }
    const existing = await QuestionPaper.findById(request.params.id).select('+lockedBy');
    if (!existing) return response.status(404).json({ success: false, message: 'Question paper not found.' });
    if (existing.status !== 'LOCKED') {
      await audit(request, 'RELEASE_SCHEDULE_DENIED', { targetType: 'QuestionPaper', targetId: existing.id, metadata: { reason: 'paper_not_locked' } });
      return response.status(409).json({ success: false, message: 'Only locked question papers can be scheduled for release.' });
    }
    if (!existing.lockedBy?.equals(request.user._id)) {
      await audit(request, 'RELEASE_SCHEDULE_DENIED', { targetType: 'QuestionPaper', targetId: existing.id, metadata: { reason: 'not_locking_authority' } });
      return response.status(403).json({ success: false, message: 'Only the authority that finalized this question paper can schedule its release.' });
    }
    if (existing.releaseStatus !== 'NOT_SCHEDULED' || existing.scheduledReleaseAt) {
      await audit(request, 'RELEASE_SCHEDULE_DENIED', { targetType: 'QuestionPaper', targetId: existing.id, metadata: { reason: 'already_scheduled' } });
      return response.status(409).json({ success: false, message: 'This question paper already has a release schedule.' });
    }
    const paper = await QuestionPaper.findOneAndUpdate({ _id: existing._id, status: 'LOCKED', lockedBy: request.user._id, releaseStatus: 'NOT_SCHEDULED', scheduledReleaseAt: null }, { $set: { scheduledReleaseAt, releaseStatus: 'SCHEDULED' } }, { new: true });
    if (!paper) return response.status(409).json({ success: false, message: 'This question paper already has a release schedule.' });
    await audit(request, 'RELEASE_SCHEDULED', { targetType: 'QuestionPaper', targetId: paper.id, metadata: { scheduledReleaseAt: paper.scheduledReleaseAt.toISOString() } });
    response.json({ success: true, releaseStatus: paper.releaseStatus, scheduledReleaseAt: paper.scheduledReleaseAt });
  } catch (error) { next(error); }
};
module.exports = { securityOfficer, examAuthority };
