const mongoose = require('mongoose');
const QuestionPaper = require('../models/QuestionPaper');
const QuestionPaperReview = require('../models/QuestionPaperReview');
const { audit } = require('../services/auditService');

const reviewerFields = '+reviewerId';
const validId = id => mongoose.isObjectIdOrHexString(id);
const safePaper = paper => ({ id: paper._id, title: paper.title, examName: paper.examName, examCode: paper.examCode, subject: paper.subject, questionPaperType: paper.questionPaperType, fileOriginalName: paper.fileOriginalName, fileMimeType: paper.fileMimeType, fileSize: paper.fileSize, hasFile: Boolean(paper.storageKey), isEncrypted: Boolean(paper.storageKey && String(paper.fileStoredName || '').endsWith('.enc')), integrityProtected: Boolean(paper.storageKey && String(paper.fileStoredName || '').endsWith('.enc')), status: paper.status, submittedAt: paper.submittedAt, createdAt: paper.createdAt, updatedAt: paper.updatedAt, reviewAssignedAt: paper.reviewAssignedAt, reviewedAt: paper.reviewedAt, reviewComment: paper.reviewComment, submittedBy: paper.createdBy?.name || undefined });
function reviewableQuery(userId) { return { $or: [{ status: 'SUBMITTED', createdBy: { $ne: userId } }, { reviewerId: userId, status: { $in: ['UNDER_REVIEW', 'REVIEWER_APPROVED', 'REVIEWER_REJECTED'] } }] }; }
async function findAccessible(request, response, action) { if (!validId(request.params.id)) { response.status(404).json({ success: false, message: 'Question paper not available for review.' }); return null; } const paper = await QuestionPaper.findOne({ _id: request.params.id, ...reviewableQuery(request.user._id) }).select(reviewerFields).populate('createdBy', 'name'); if (!paper) { await audit(request, 'REVIEWER_PAPER_ACCESS_DENIED', { targetType: 'QuestionPaper', targetId: request.params.id, metadata: { action } }); response.status(404).json({ success: false, message: 'Question paper not available for review.' }); return null; } return paper; }
function commentFrom(request, required) { const comment = typeof request.body?.comment === 'string' ? request.body.comment.trim() : ''; if (required && comment.length < 5) return null; return comment || null; }

async function dashboardStats(request, response, next) { try { const userId = request.user._id; const [pending, underReview, approved, rejected, recent] = await Promise.all([QuestionPaper.countDocuments({ status: 'SUBMITTED', createdBy: { $ne: userId } }), QuestionPaper.countDocuments({ status: 'UNDER_REVIEW', reviewerId: userId }), QuestionPaper.countDocuments({ status: 'REVIEWER_APPROVED', reviewerId: userId }), QuestionPaper.countDocuments({ status: 'REVIEWER_REJECTED', reviewerId: userId }), QuestionPaperReview.find({ reviewerId: userId }).sort({ createdAt: -1 }).limit(5).populate('paperId', 'title').lean()]); await audit(request, 'REVIEWER_DASHBOARD_VIEWED'); response.json({ success: true, stats: { pending, underReview, approved, rejected }, recent: recent.map(item => ({ action: item.action, comment: item.comment, createdAt: item.createdAt, paperTitle: item.paperId?.title || 'Question paper' })) }); } catch (error) { next(error); } }
async function listPapers(request, response, next) { try { const papers = await QuestionPaper.find(reviewableQuery(request.user._id)).select(reviewerFields).populate('createdBy', 'name').sort({ submittedAt: -1, updatedAt: -1 }).lean(); response.json({ success: true, papers: papers.map(safePaper) }); } catch (error) { next(error); } }
async function getPaper(request, response, next) { try { const paper = await findAccessible(request, response, 'VIEW'); if (!paper) return; await audit(request, 'REVIEWER_PAPER_VIEWED', { targetType: 'QuestionPaper', targetId: paper.id }); response.json({ success: true, paper: safePaper(paper) }); } catch (error) { next(error); } }
async function claimPaper(request, response, next) { try { if (!validId(request.params.id)) return response.status(404).json({ success: false, message: 'Question paper not available for review.' }); const paper = await QuestionPaper.findOneAndUpdate({ _id: request.params.id, status: 'SUBMITTED', createdBy: { $ne: request.user._id }, reviewerId: null }, { $set: { status: 'UNDER_REVIEW', reviewerId: request.user._id, reviewAssignedAt: new Date(), reviewedAt: null, reviewComment: null } }, { new: true }).select(reviewerFields).populate('createdBy', 'name'); if (!paper) { const ownPaper = await QuestionPaper.exists({ _id: request.params.id, createdBy: request.user._id }); await audit(request, ownPaper ? 'REVIEWER_SELF_REVIEW_ATTEMPT' : 'REVIEW_ASSIGNMENT_CONFLICT', { targetType: 'QuestionPaper', targetId: request.params.id }); return response.status(ownPaper ? 403 : 409).json({ success: false, message: ownPaper ? 'You cannot review your own question paper.' : 'Question paper is no longer available for review.' }); } await QuestionPaperReview.create({ paperId: paper._id, reviewerId: request.user._id, action: 'CLAIMED' }); await audit(request, 'REVIEWER_PAPER_CLAIMED', { targetType: 'QuestionPaper', targetId: paper.id }); response.json({ success: true, paper: safePaper(paper) }); } catch (error) { next(error); } }
async function decidePaper(request, response, next, action) { try { if (!validId(request.params.id)) return response.status(404).json({ success: false, message: 'Question paper not available for review.' }); const comment = commentFrom(request, action === 'REJECTED'); if (action === 'REJECTED' && !comment) return response.status(400).json({ success: false, message: 'A rejection reason of at least 5 characters is required.' }); const status = action === 'APPROVED' ? 'REVIEWER_APPROVED' : 'REVIEWER_REJECTED'; const paper = await QuestionPaper.findOneAndUpdate({ _id: request.params.id, status: 'UNDER_REVIEW', reviewerId: request.user._id, createdBy: { $ne: request.user._id } }, { $set: { status, reviewedAt: new Date(), reviewComment: comment } }, { new: true }).select(reviewerFields).populate('createdBy', 'name'); if (!paper) { const ownPaper = await QuestionPaper.exists({ _id: request.params.id, createdBy: request.user._id }); await audit(request, ownPaper ? 'REVIEWER_SELF_REVIEW_ATTEMPT' : 'REVIEWER_INVALID_TRANSITION', { targetType: 'QuestionPaper', targetId: request.params.id, metadata: { action } }); return response.status(ownPaper ? 403 : 409).json({ success: false, message: ownPaper ? 'You cannot review your own question paper.' : 'Question paper is not assigned for this review action.' }); } await QuestionPaperReview.create({ paperId: paper._id, reviewerId: request.user._id, action, comment }); await audit(request, action === 'APPROVED' ? 'REVIEWER_PAPER_APPROVED' : 'REVIEWER_PAPER_REJECTED', { targetType: 'QuestionPaper', targetId: paper.id }); response.json({ success: true, paper: safePaper(paper) }); } catch (error) { next(error); } }
const approvePaper = (request, response, next) => decidePaper(request, response, next, 'APPROVED');
const rejectPaper = (request, response, next) => decidePaper(request, response, next, 'REJECTED');
async function listReviews(request, response, next) { try { const paper = await findAccessible(request, response, 'REVIEW_HISTORY'); if (!paper) return; const reviews = await QuestionPaperReview.find({ paperId: paper._id }).sort({ createdAt: 1 }).populate('reviewerId', 'name').lean(); response.json({ success: true, reviews: reviews.map(review => ({ action: review.action, comment: review.comment, createdAt: review.createdAt, reviewerName: review.reviewerId?.name || 'Reviewer' })) }); } catch (error) { next(error); } }

module.exports = { dashboardStats, listPapers, getPaper, claimPaper, approvePaper, rejectPaper, listReviews, findAccessible };
