import React, { useEffect, useState } from 'react';
import api from '../services/api';
const roles = ['', 'ADMIN', 'QUESTION_SETTER', 'REVIEWER', 'SECURITY_OFFICER', 'EXAM_AUTHORITY', 'EXAM_CENTER'];
export default function AdminUsersPage() {
  const [users, setUsers] = useState([]), [pagination, setPagination] = useState({ page: 1, totalPages: 1 }), [filters, setFilters] = useState({ search: '', role: '', isActive: '' }), [query, setQuery] = useState(''), [state, setState] = useState({ loading: true, error: '', message: '' });
  async function load(page = pagination.page, current = filters) { setState(s => ({ ...s, loading: true, error: '' })); try { const { data } = await api.get('/admin/users', { params: { page, limit: 10, ...current } }); setUsers(data.users); setPagination(data.pagination); } catch (e) { setState(s => ({ ...s, error: e.response?.data?.message || 'Unable to load users. Please try again.' })); } finally { setState(s => ({ ...s, loading: false })); } }
  useEffect(() => { load(1); }, []);
  function apply(event) { event.preventDefault(); const next = { ...filters, search: query }; setFilters(next); load(1, next); }
  async function changeStatus(user) { const verb = user.isActive ? 'deactivate' : 'activate'; if (!window.confirm(`Are you sure you want to ${verb} ${user.name}?`)) return; try { await api.patch(`/admin/users/${user.id}/status`, { isActive: !user.isActive }); setState(s => ({ ...s, message: `User ${verb}d successfully.` })); load(); } catch (e) { setState(s => ({ ...s, error: e.response?.data?.message || 'Unable to update account status.' })); } }
  return <section><div className="page-title"><div><p className="eyebrow">USER MANAGEMENT</p><h1>Users</h1></div></div><form className="filters" onSubmit={apply}><input placeholder="Search by name or email" value={query} onChange={e => setQuery(e.target.value)} /><select value={filters.role} onChange={e => { const next = { ...filters, role: e.target.value }; setFilters(next); load(1, next); }}>{roles.map(role => <option key={role} value={role}>{role || 'All Roles'}</option>)}</select><select value={filters.isActive} onChange={e => { const next = { ...filters, isActive: e.target.value }; setFilters(next); load(1, next); }}><option value="">All Users</option><option value="true">Active</option><option value="false">Inactive</option></select><button>Search</button><button className="secondary" type="button" onClick={() => { setQuery(''); const next = { search: '', role: '', isActive: '' }; setFilters(next); load(1, next); }}>Clear</button></form>{state.message && <p className="form-success">{state.message}</p>}{state.error && <p className="form-error">{state.error}</p>}{state.loading ? <p>Loading users…</p> : users.length === 0 ? <p className="empty">No users found.</p> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th>Last Login</th><th>Action</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{user.role}</td><td><span className={`badge ${user.isActive ? 'active' : 'inactive'}`}>{user.isActive ? 'Active' : 'Inactive'}</span></td><td>{new Date(user.createdAt).toLocaleDateString()}</td><td>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : 'Never'}</td><td><button className="small" onClick={() => changeStatus(user)}>{user.isActive ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div>}<div className="pagination"><button className="secondary" disabled={pagination.page <= 1} onClick={() => load(pagination.page - 1)}>Previous</button><span>Page {pagination.page} of {pagination.totalPages || 1}</span><button disabled={pagination.page >= pagination.totalPages} onClick={() => load(pagination.page + 1)}>Next</button></div></section>;
}
