import React, { useEffect, useState } from 'react';
import api from '../services/api';
export default function AdminExamCentersPage() {
  const [form, setForm] = useState({ name: '', email: '', password: '' }), [centers, setCenters] = useState([]), [state, setState] = useState({ loading: true, error: '', message: '' });
  async function load() { setState(s => ({ ...s, loading: true })); try { const { data } = await api.get('/admin/exam-centers', { params: { limit: 100 } }); setCenters(data.users); } catch (e) { setState(s => ({ ...s, error: e.response?.data?.message || 'Unable to load Exam Centres.' })); } finally { setState(s => ({ ...s, loading: false })); } }
  useEffect(() => { load(); }, []);
  async function create(event) { event.preventDefault(); setState(s => ({ ...s, error: '', message: '' })); try { await api.post('/admin/exam-centers', form); setForm({ name: '', email: '', password: '' }); setState(s => ({ ...s, message: 'Exam Centre account created.' })); load(); } catch (e) { setState(s => ({ ...s, error: e.response?.data?.message || 'Unable to create Exam Centre.' })); } }
  async function status(center) { if (!window.confirm(`Change status for ${center.name}?`)) return; try { await api.patch(`/admin/users/${center.id}/status`, { isActive: !center.isActive }); load(); } catch (e) { setState(s => ({ ...s, error: e.response?.data?.message || 'Unable to update centre.' })); } }
  return <section><p className="eyebrow">EXAM CENTRE MANAGEMENT</p><h1>Exam Centres</h1><form className="create-form" onSubmit={create}><input required placeholder="Centre name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /><input required type="email" placeholder="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><input required type="password" minLength="8" placeholder="Temporary password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /><button>Create Exam Centre</button></form>{state.message && <p className="form-success">{state.message}</p>}{state.error && <p className="form-error">{state.error}</p>}{state.loading ? <p>Loading Exam Centres…</p> : centers.length === 0 ? <p className="empty">No Exam Centres found.</p> : <div className="table-wrap"><table><thead><tr><th>Centre</th><th>Email</th><th>Status</th><th>Created</th><th>Created By</th><th>Last Login</th><th>Action</th></tr></thead><tbody>{centers.map(center => <tr key={center.id}><td>{center.name}</td><td>{center.email}</td><td><span className={`badge ${center.isActive ? 'active' : 'inactive'}`}>{center.isActive ? 'Active' : 'Inactive'}</span></td><td>{new Date(center.createdAt).toLocaleDateString()}</td><td>{center.createdBy?.name || '—'}</td><td>{center.lastLoginAt ? new Date(center.lastLoginAt).toLocaleString() : 'Never'}</td><td><button className="small" onClick={() => status(center)}>{center.isActive ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table></div>}</section>;
}
