import React, { useEffect, useState } from 'react';
import api from '../services/api';

const formatDate = value => value ? new Date(value).toLocaleString() : '—';
const isAvailable = paper => paper.releaseStatus === 'RELEASED' || new Date(paper.scheduledReleaseAt).getTime() <= Date.now();
async function releaseError(error) { const payload = error.response?.data; if (payload instanceof Blob) { try { return JSON.parse(await payload.text()).message; } catch {} } if (payload?.message) return payload.message; if (error.response?.status === 401 || error.response?.status === 403) return 'This question paper is not yet released or you are not authorized to access it.'; if (error.response?.status === 404) return 'This question paper is unavailable.'; if (error.response?.status === 422) return 'Integrity or blockchain verification failed. The question paper cannot be accessed.'; return 'The secure release service is unavailable. Please try again.'; }

function PaperTable({ papers, available, onAccess, busy }) { return papers.length ? <div className="table-wrap"><table><thead><tr><th>Paper</th><th>Exam / Subject</th><th>Status</th><th>Scheduled release</th><th>Action</th></tr></thead><tbody>{papers.map(paper => <tr key={paper.id}><td>{paper.title}<br /><small>{paper.questionPaperType || '—'}</small></td><td>{paper.examName}{paper.examCode ? ` (${paper.examCode})` : ''}<br /><small>{paper.subject}</small></td><td><span className={`badge ${available ? 'active' : 'submitted'}`}>{available ? 'RELEASED' : 'SCHEDULED'}</span></td><td>{formatDate(paper.scheduledReleaseAt)}</td><td>{available ? <button className="small" disabled={busy === paper.id} onClick={() => onAccess(paper.id)}>{busy === paper.id ? 'Opening…' : 'Access Question Paper'}</button> : <button className="small secondary" disabled>Not yet available</button>}</td></tr>)}</tbody></table></div> : <p className="empty">No question papers are {available ? 'released' : 'scheduled'}.</p>; }

export default function ExamCenterPapersPage() { const [papers, setPapers] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const load = () => api.get('/question-papers/exam-center').then(({ data }) => setPapers(data.papers)).catch(requestError => setError(requestError.response?.data?.message || 'Unable to load question papers.')); useEffect(() => { load(); }, []); async function access(id) { setBusy(id); setError(''); try { const response = await api.get(`/question-papers/${id}/release`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.target = '_blank'; link.rel = 'noopener noreferrer'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 60_000); await load(); } catch (requestError) { setError(await releaseError(requestError)); } finally { setBusy(''); } } const available = papers.filter(isAvailable); const scheduled = papers.filter(paper => !isAvailable(paper)); return <section><p className="eyebrow">SECURE RELEASE</p><h1>Question Papers</h1>{error && <p className="form-error">{error}</p>}<h2>Released Question Papers</h2><PaperTable papers={available} available onAccess={access} busy={busy} /><h2>Scheduled Question Papers</h2><PaperTable papers={scheduled} available={false} onAccess={access} busy={busy} /></section>; }
