import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
const maxSize = 10 * 1024 * 1024;
export default function QuestionSetterPaperCreatePage() {
  const navigate = useNavigate(); const [form, setForm] = useState({ title: '', examName: '', examCode: '', subject: '', questionPaperType: '', description: '' }); const [file, setFile] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  function selectFile(event) { const selected = event.target.files[0]; setFile(selected || null); if (selected && (selected.type !== 'application/pdf' || selected.size > maxSize)) setError(selected.type !== 'application/pdf' ? 'Only PDF files are allowed.' : 'PDF files must not exceed 10 MB.'); else setError(''); }
  async function submit(event) { event.preventDefault(); if (!form.title.trim() || !form.examName.trim() || !form.subject.trim()) return setError('Title, exam name, and subject are required.'); if (!file) return setError('A PDF file is required.'); if (file.type !== 'application/pdf' || file.size > maxSize) return setError('Choose a PDF file no larger than 10 MB.'); setSaving(true); setError(''); try { const created = await api.post('/question-papers', form); const body = new FormData(); body.append('file', file); await api.post(`/question-papers/${created.data.paper.id}/upload`, body); navigate('/question-setter/papers'); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to create the question paper.'); } finally { setSaving(false); } }
  return <section><p className="eyebrow">NEW DRAFT</p><h1>Create Question Paper</h1><form className="paper-form" onSubmit={submit}><label>Paper Title<input value={form.title} maxLength="200" onChange={e => setForm({ ...form, title: e.target.value })} required /></label><label>Exam Name<input value={form.examName} maxLength="200" onChange={e => setForm({ ...form, examName: e.target.value })} required /></label><label>Exam Code<input value={form.examCode} maxLength="100" onChange={e => setForm({ ...form, examCode: e.target.value })} /></label><label>Subject<input value={form.subject} maxLength="200" onChange={e => setForm({ ...form, subject: e.target.value })} required /></label><label>Question Paper Type<input value={form.questionPaperType} maxLength="100" onChange={e => setForm({ ...form, questionPaperType: e.target.value })} /></label><label>Description<textarea value={form.description} maxLength="2000" onChange={e => setForm({ ...form, description: e.target.value })} /></label><label>PDF File<input type="file" accept="application/pdf" onChange={selectFile} required /></label><small>Only PDF files are allowed. Maximum file size is 10 MB.</small>{error && <p className="form-error">{error}</p>}<button disabled={saving}>{saving ? 'Creating…' : 'Create and Upload'}</button></form></section>;
}
