import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api from '../services/api';
const roles = ['QUESTION_SETTER', 'REVIEWER', 'SECURITY_OFFICER', 'EXAM_AUTHORITY'];
export default function RegisterPage() {
  const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '', role: roles[0] }); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const navigate = useNavigate();
  async function submit(event) { event.preventDefault(); setError(''); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); try { await api.post('/auth/register', form); setMessage('Registration successful. Redirecting to sign in…'); setTimeout(() => navigate('/login'), 900); } catch (e) { setError(e.response?.data?.message || 'Unable to register.'); } }
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><p className="eyebrow">PUBLIC REGISTRATION</p><h1>Create account</h1>{error && <p className="form-error">{error}</p>}{message && <p className="form-success">{message}</p>}<label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Role<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })}>{roles.map(role => <option key={role}>{role}</option>)}</select></label><label>Password<input required type="password" minLength="8" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><label>Confirm password<input required type="password" minLength="8" value={form.confirmPassword} onChange={e => setForm({ ...form, confirmPassword: e.target.value })} /></label><button>Create account</button><p>Already registered? <Link to="/login">Sign in</Link></p></form></main>;
}
