import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import api from '../services/api';

const formatDate = value => value ? new Date(value).toLocaleString() : '—';
export default function ReviewerPaperReviewPage() {
  const { id } = useParams(); const [paper, setPaper] = useState(null); const [reviews, setReviews] = useState([]); const [comment, setComment] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => Promise.all([api.get(`/reviewer/question-papers/${id}`), api.get(`/reviewer/question-papers/${id}/reviews`)]).then(([paperResponse, historyResponse]) => { setPaper(paperResponse.data.paper); setReviews(historyResponse.data.reviews); }).catch(requestError => setError(requestError.response?.data?.message || 'Unable to load this question paper.'));
  useEffect(() => { load(); }, [id]);
  async function download() { setBusy(true); try { const response = await api.get(`/question-papers/${id}/download`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = 'question-paper.pdf'; link.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(requestError.response?.data?.message || 'Question paper file is unavailable.'); } finally { setBusy(false); } }
  async function decide(action) { if (action === 'reject' && comment.trim().length < 5) return setError('Enter a rejection reason of at least 5 characters.'); if (action === 'approve' && !window.confirm('Approve this question paper for the next review phase?')) return; setBusy(true); try { await api.post(`/reviewer/question-papers/${id}/${action}`, { comment }); setComment(''); load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to record the review decision.'); } finally { setBusy(false); } }
  if (!paper) return <section><Link to="/reviewer/papers">Back to review queue</Link>{error && <p className="form-error">{error}</p>}</section>;
  const assigned = paper.status === 'UNDER_REVIEW';
  return <section><Link to="/reviewer/papers">Back to review queue</Link><p className="eyebrow">SECURE REVIEW</p><h1>{paper.title}</h1>{error && <p className="form-error">{error}</p>}<div className="stats-grid"><article className="stat-card"><span>Exam</span><strong>{paper.examName}</strong><small>{paper.subject}</small></article><article className="stat-card"><span>Submitted by</span><strong>{paper.submittedBy || 'Question Setter'}</strong><small>{formatDate(paper.submittedAt)}</small></article><article className="stat-card"><span>Status</span><strong>{paper.status}</strong><small>{paper.fileOriginalName || 'No PDF attached'}</small></article></div><div className="paper-actions"><button onClick={download} disabled={!paper.hasFile || busy}>Open secure PDF</button></div>{assigned && <div className="review-form"><h2>Review decision</h2><label>Comments <textarea value={comment} onChange={event => setComment(event.target.value)} maxLength="2000" placeholder="Required for rejection" /></label><div className="paper-actions"><button onClick={() => decide('approve')} disabled={busy}>Approve</button><button className="danger" onClick={() => decide('reject')} disabled={busy}>Reject</button></div></div>}<h2>Review history</h2>{reviews.length ? <div className="activity-list">{reviews.map((review, index) => <p key={`${review.createdAt}-${index}`}><span>{review.action}{review.comment ? ` · ${review.comment}` : ''}</span><small>{formatDate(review.createdAt)}</small></p>)}</div> : <p className="empty">No review history yet.</p>}</section>;
}
