import React, { useRef, useState } from 'react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import { dashboardPathForRole } from '../utils/roleDashboard';
export default function VerifyOtpPage() {
  const location = useLocation(); const challengeId = location.state?.challengeId; const verificationCompletedRef = useRef(false); const [otp, setOtp] = useState(''); const [demoOtp, setDemoOtp] = useState(() => location.state?.demoOtp || null); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const navigate = useNavigate(); const { finishLogin } = useAuth();
  if (!challengeId && !verificationCompletedRef.current) return <Navigate to="/login" replace />;
  async function submit(event) { event.preventDefault(); setError(''); setNotice(''); try { const { data } = await api.post('/auth/verify-otp', { challengeId, otp }); const dashboardPath = dashboardPathForRole(data.user.role); if (!dashboardPath) throw new Error('Your account does not have a supported dashboard.'); verificationCompletedRef.current = true; finishLogin(data.token, data.user); navigate(dashboardPath, { replace: true }); } catch (e) { setError(e.response?.data?.message || 'Verification failed.'); } }
  async function resend() { setError(''); setNotice(''); try { const { data } = await api.post('/auth/resend-otp', { challengeId }); setDemoOtp(data.demoOtp || null); setOtp(''); setNotice(data.demoOtp ? 'A new demo OTP was generated.' : 'A new OTP was generated.'); } catch (e) { setError(e.response?.data?.message || 'Unable to resend OTP.'); } }
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><p className="eyebrow">MULTI-FACTOR AUTHENTICATION</p><h1>Verify OTP</h1><p>{demoOtp ? 'Use the OTP below to complete verification.' : 'Enter the OTP sent to your registered contact.'}</p>{demoOtp && <section className="demo-otp" aria-live="polite"><span>DEMO MODE</span><strong>Demo/Deployment OTP</strong><code>{demoOtp}</code><small>This OTP expires in 5 minutes.</small></section>}{error && <p className="form-error">{error}</p>}{notice && <p className="form-success">{notice}</p>}<label>OTP<input required inputMode="numeric" pattern="[0-9]{6}" maxLength="6" value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, ''))} /></label><button>Verify and sign in</button><button type="button" className="secondary" onClick={resend}>Resend OTP</button></form></main>;
}
